#!/usr/bin/env bash

cd ../shr_spec
echo "===================== shr_spec ====================="
git pull

cd ../shr-models
echo "==================== shr-models ===================="
git pull

cd ../shr-test-helpers
echo "================= shr-test-helpers ================="
git pull

cd ../shr-expand
echo "==================== shr-expand ===================="
git pull

cd ../shr-text-import
echo "================= shr-text-import =================="
git pull

cd ../shr-json-schema-export
echo "============== shr-json-schema-export =============="
git pull

cd ../shr-json-javadoc
echo "============== shr-json-javadoc =============="
git pull

cd ../shr-es6-export
echo "================== shr-es6-export =================="
git pull

cd ../shr-fhir-export
echo "================= shr-fhir-export =================="
git pull

cd ../shr-cli
echo "===================== shr-cli ======================"
git pull
