#!/usr/bin/env bash

yarn cache clean

cd ../shr-models
rm -rf node_modules
yarn

cd ../shr-test-helpers
rm -rf node_modules
yarn

cd ../shr-expand
rm -rf node_modules
yarn

cd ../shr-text-import
rm -rf node_modules
yarn

cd ../shr-json-export
rm -rf node_modules
yarn

cd ../shr-fhir-export
rm -rf node_modules
yarn

cd ../shr-cli
rm -rf node_modules
yarn
