#!/usr/bin/env bash

echo "===================== shr-cli ======================"
yarn unlink shr-fhir-export
yarn unlink shr-es6-export
yarn unlink shr-json-schema-export
yarn unlink shr-json-javadoc
yarn unlink shr-data-dict-export
yarn unlink shr-text-import
yarn unlink shr-expand
yarn unlink shr-models

cd ../shr-data-dict-export
echo "============== shr-data-dict-export ================"
yarn unlink shr-models
yarn unlink

cd ../shr-es6-export
echo "================== shr-es6-export =================="
yarn unlink shr-models
yarn unlink shr-text-import
yarn unlink shr-expand
yarn unlink shr-json-schema-export
yarn unlink shr-test-helpers
yarn unlink shr-fhir-export
yarn unlink

cd ../shr-fhir-export
echo "================= shr-fhir-export =================="
yarn unlink shr-models
yarn unlink shr-test-helpers
yarn unlink

cd ../shr-json-schema-export
echo "============== shr-json-schema-export =============="
yarn unlink shr-models
yarn unlink shr-expand
yarn unlink shr-test-helpers
yarn unlink

cd ../shr-json-javadoc
echo "============== shr-json-javadoc ===================="
yarn unlink

cd ../shr-text-import
echo "================= shr-text-import =================="
yarn unlink shr-models
yarn unlink shr-expand
yarn unlink shr-test-helpers
yarn unlink

cd ../shr-expand
echo "==================== shr-expand ===================="
yarn unlink shr-models
yarn unlink shr-test-helpers
yarn unlink

cd ../shr-test-helpers
echo "================= shr-test-helpers ================="
yarn unlink shr-models
yarn unlink

cd ../shr-models
echo "==================== shr-models ===================="
yarn unlink

cd ../shr-cli
