#!/usr/bin/env bash

cd ../shr-models
yarn link

cd ../shr-test-helpers
yarn link shr-models
yarn link

cd ../shr-expand
yarn link shr-models
yarn link shr-test-helpers
yarn link

cd ../shr-text-import
yarn link shr-models
yarn link shr-test-helpers
yarn link

cd ../shr-json-export
yarn link shr-models
yarn link shr-test-helpers
yarn link

cd ../shr-md-export
yarn link shr-models
yarn link shr-test-helpers
yarn link

cd ../shr-fhir-export
yarn link shr-models
yarn link shr-test-helpers
yarn link

cd ../shr-cli
yarn link shr-models
yarn link shr-expand
yarn link shr-text-import
yarn link shr-json-export
yarn link shr-md-export
yarn link shr-fhir-export
